services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MODAL_ML_URL=https://ieraasyl--indrive-vehicle-inspector-fastapi-app.modal.run/predict
      - USE_LOCAL_MODELS=true
    volumes:
      - ./backend:/code
      - ./models:/code/models  # Mount models directory
    command: uvicorn app.server:app --host 0.0.0.0 --port 8000 --reload
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s  # Allow time for model loading

  frontend:
    build: ./frontend  
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy  # Wait for backend to be healthy (models loaded)
    command: npm run dev -- --host 0.0.0.0